# -*- coding: utf-8 -*-
{
    "name": "EduTek - Ecole Primaire (Cameroun)",
    "version": "19.0.2.34.0",
    "author": "Custom",
    "category": "Education",
    "summary": "Gestion simplifiee des classes, notes, bulletins et frais scolaires pour le primaire",
    "description": "Module complementaire a EduTek Core pour la gestion des ecoles primaires "
                    "camerounaises : classes, programme/coefficients, notes, bulletins trimestriels "
                    "avec moyenne et rang, et frais scolaires lies a la comptabilite.",
    "depends": ["edutek_core", "account", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/op_staff_type_data.xml",
        "data/op_education_structure_data.xml",
        "data/ir_cron_data.xml",
        "views/op_classe_views.xml",
        "views/op_student_views.xml",
        "views/op_student_enrollment_history_views.xml",
        "views/op_student_mark_views.xml",
        "views/op_bulletin_views.xml",
        "views/op_fee_views.xml",
        "views/op_bank_receipt_views.xml",
        "data/default_fee_types.xml",
        "views/op_student_change_classe_wizard_views.xml",
        "views/op_classe_fee_bilan_wizard_views.xml",
        "views/op_student_list_wizard_views.xml",
        "views/op_student_insolvable_wizard_views.xml",
        "views/op_student_import_wizard_views.xml",
        "views/op_student_registration_list_wizard_views.xml",
        "views/op_cash_collection_wizard_views.xml",
        "views/op_database_backup_wizard_views.xml",
        "views/op_employee_list_wizard_views.xml",
        "views/op_classe_list_wizard_views.xml",
        "views/op_student_fee_list_wizard_views.xml",
        "views/op_student_mark_list_wizard_views.xml",
        "views/op_bulletin_list_wizard_views.xml",
        "views/hr_employee_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_cleanup.xml",
        "report/report_letterhead.xml",
        "report/op_bulletin_report.xml",
        "report/op_student_fee_receipt_report.xml",
        "report/op_student_list_report.xml",
        "report/op_student_registration_list_report.xml",
        "report/op_cash_collection_daily_report.xml",
        "report/op_cash_collection_ledger_report.xml",
        "report/report_student_idcard_inherit.xml",
        "report/report_student_bonafide_inherit.xml",
        "report/op_student_insolvable_report.xml",
        "report/op_classe_fee_bilan_report.xml",
        "report/op_employee_list_report.xml",
        "report/op_classe_list_report.xml",
        "report/op_student_fee_list_report.xml",
        "report/op_student_mark_list_report.xml",
        "report/op_bulletin_list_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "edutek_primaire_cm/static/src/academic_year_switcher.js",
            "edutek_primaire_cm/static/src/academic_year_switcher.xml",
            "edutek_primaire_cm/static/src/form_status_indicator_patch.js",
            "edutek_primaire_cm/static/src/form_status_indicator_patch.xml",
            "edutek_primaire_cm/static/src/fee_generate_loader.js",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": True,
    "license": "LGPL-3",
}
