# -*- coding: utf-8 -*-
from . import hr_employee
from . import res_users
from . import res_company
from . import op_classe
from . import op_exam
from . import op_document_type
from . import mail_template
from . import sms_template
from . import op_scholarship
from . import op_fee_reduction
from . import res_config_settings
from . import op_end_cycle_certificate
from . import op_payment_moratorium
from . import op_work_certificate
from . import op_internship
from . import op_admission_application
from . import op_school_document_type
from . import op_student_document
from . import op_student
from . import op_student_fee
from . import op_academic_year
